image: node:latest

default:
  tags: 
    - test-runner

stages:     
#   - install    
#   - build
  - test
  # - deploy

# install:
#    stage: install
#    script:
#       - rm -rf node_modules
#       - npm install
#    cache:
#     key: ${CI_BUILD_REF_NAME}
#     paths:
#       - node_modules/
#    artifacts:
#     paths:
#       - node_modules/


# build:
#    stage: build
#    script:
#       - CI=false npm run build
#    artifacts:
#       paths:
#          - build
#       expire_in: 30 mins
#    dependencies:
#       - install

test:
  image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
  stage: test
  before_script:
    - npm install
  script:
    - npm ci
    # start the server in the background
    - npm start &
    # run Cypress tests
    - npx cypress run --browser chrome
  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
    expire_in: 1 day
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  


# unit-test-job:   
#   stage: test    
#   script:
#     - echo "Running unit tests... This will take about 60 seconds."
#     - sleep 60
#     - echo "Code coverage is 90%"

# lint-test-job:   
#   stage: test    
#   script:
#     - echo "Linting code... This will take about 10 seconds."
#     - sleep 10
#     - echo "No lint issues found."

# deploy-job:      
#   stage: deploy  
#   environment: production
#   script:
#     - echo "Deploying application..."
#     - echo "Application successfully deployed."
