image: node:22

default:
  tags: 
    - test-runner

stages:         
  - build
  - test
  # - deploy


build:
  stage: build
  script:
    - yarn
  cache:
    paths:
      - node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - node_modules/

test:
  stage: test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  dependencies:
    - build
  script:
    - jest --coverage
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml 
  


# unit-test-job:   
#   stage: test    
#   script:
#     - echo "Running unit tests... This will take about 60 seconds."
#     - sleep 60
#     - echo "Code coverage is 90%"

# lint-test-job:   
#   stage: test    
#   script:
#     - echo "Linting code... This will take about 10 seconds."
#     - sleep 10
#     - echo "No lint issues found."

# deploy-job:      
#   stage: deploy  
#   environment: production
#   script:
#     - echo "Deploying application..."
#     - echo "Application successfully deployed."
