image: node:latest

default:
  tags: 
    - test-runner

stages:     
  - install    
  - build
  - test
  # - deploy

install:
   stage: install
   script:
      - npm install


build:
   stage: build
   script:
      - CI=false npm run build
   artifacts:
      paths:
         - build
      expire_in: 30 mins
   dependencies:
      - install

test:
  stage: test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  dependencies:
    - install
  script:
    - jest --coverage
  


# unit-test-job:   
#   stage: test    
#   script:
#     - echo "Running unit tests... This will take about 60 seconds."
#     - sleep 60
#     - echo "Code coverage is 90%"

# lint-test-job:   
#   stage: test    
#   script:
#     - echo "Linting code... This will take about 10 seconds."
#     - sleep 10
#     - echo "No lint issues found."

# deploy-job:      
#   stage: deploy  
#   environment: production
#   script:
#     - echo "Deploying application..."
#     - echo "Application successfully deployed."
