version: '3'

services:
  frontend:
    container_name: frontend
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: 'host'
